# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-intel"
    "msi-ec"
  ];
  boot.extraModulePackages = with config.boot.kernelPackages; [
    msi-ec
  ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-5728c9af-d0fb-40ec-8046-f39eb545c669";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-5728c9af-d0fb-40ec-8046-f39eb545c669".device =
    "/dev/disk/by-uuid/5728c9af-d0fb-40ec-8046-f39eb545c669";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7FC7-1054";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 16 * 1024;
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.nvidia = {
    open = true;
    modesetting.enable = true;
    powerManagement.enable = false;
    nvidiaSettings = true;
  };
}
