import = ["/home/pablo/.config/alacritty/catppuccin-mocha.toml"]

[cursor.style]
shape = "Beam"

[font]
size = 12.0
[font.normal]
family = "MonaspiceNe Nerd Font"
style = "Regular"
[font.bold_italic]
family = "MonaspiceNe Nerd Font"
style = "Bold Italic"
[font.bold]
family = "MonaspiceNe Nerd Font"
style = "Bold"
[font.italic]
family = "MonaspiceNe Nerd Font"
style = "Italic"

[window]
opacity = 0.9
decorations = "None"

[window.padding]
x = 15
y = 15
